### ISSUE TITLE
configure tls certs better for ALBs

### ISSUE THREAD

**Issue by thecaffiend** [cape-ph/cape-cod#166]
***Related to*** #125 

Right now, they are defined with the static app the cert is used for in the config. This is problematic because the cert is associated with the ALB listener, which is defined per port/protocol combo. So if you had a number of apps/apis behind the ALB all expecting traffic on HTTPS/443, then you could only use one cert for that. So we need to rethink the config for this.

This needs to also be done in a way that doesn't cause problems for configuring ALBs for APIs and non-static apps.

A potential config layout change (not well thought out yet) is something like (with `albs` replacing the current `static-apps` config hierarchy)
```
albs:
    # this becomes the ALB ID used in a few functions
    - name: static
      # it would be cool to also have other listener stuff here so we could do other ports/protocols
      tls:
          dir: "./assets-untracked/tls/dap-ui"
          ca-cert: "ca.crt"
          server-key: "analysis-pipelines.cape-dev.org.key"
          server-cert: "analysis-pipelines.cape-dev.org.crt"
      apps:
          # This is very specific to static apps, so this is going to need some work
          - name: "dap-ui"
            # this becomes the bucket name for a static site
            fqdn: "analysis-pipelines.cape-dev.org"
            dir: "./assets/web/static/dap-ui"
            files:
                - path: "nested/index.html"
                  content-type: "text/html"
                - path: "nested/request-dap/index.html"
                  content-type: "text/html"
```
